
---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:

    - name: Install docker required packages
      apt:
        update_cache: yes
        state: present
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
      tags:
        - docker

    - name: Add docker's GPG
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker

    - name: Verify that we have the key with the fingerprint
      apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker

    - name: Set up the stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Update apt packages
      apt:
        update_cache: yes
      tags:
        - docker

    - name: Install docker
      apt:
        update_cache: yes
        state: present
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
      tags:
        - docker

    - name: Add remote "ansible" user to "docker" group
      user:
        name: "ansible"
        group: "docker"
        append: yes
      tags:
        - docker

    - name: Ensure docker-compose is installed and available
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.7.0-rc1/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
      tags:
        - compose
