---
- hosts: all
  become: yes
  tasks:

    - name: Ensure that git is installed
      apt:
        update_cache: yes
        state: present
        name: 
          - git

    - name: Clone the git repository
      git:
        repo: https://github.com/thantez/sample_expressjs_github_actions_redis_project.git
        dest: /home/ansible/repo
        clone: yes

    - name: Ensure python is python3 and docker module and pip are installed
      apt:
        update_cache: yes
        state: present
        name: 
          - python-is-python3
          - python3-docker
          - pip

    - name: Install docker-compose python package
      ansible.builtin.pip:
        name: docker-compose

    - name: Deploy app by docker compose file
      docker_compose:
        project_src: /home/ansible/repo
